#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.php$')

if [ -z "$STAGED_FILES" ]; then
    printf "ℹ️  Formatting not needed, no PHP files staged\n"

    exit 0
fi

if vendor/bin/pint $STAGED_FILES >/dev/null 2>&1; then
    printf "✅ Formatting passed!\n"
else
    printf "❌ Formatting failed. Fix the formatting and try again.\n"
    exit 1
fi

exit 0