#!/bin/sh

CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.php$')

if [ -z "$CHANGED_FILES" ]; then
    printf "ℹ️  Formatting not needed, no PHP files changed\n"

    exit 0
fi

if vendor/bin/pint >/dev/null 2>&1; then
    printf "✅ Formatting passed!\n"
else
    printf "❌ Formatting failed. Fix the formatting and try again.\n"
fi

git add .

exit 0