#!/bin/sh

CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.php$')

if [ -z "$CHANGED_FILES" ]; then
    printf "ℹ️  Syntax check not needed, no PHP files changed\n"

    exit 0
fi

for file in $CHANGED_FILES; do
    php -l "$file" > /dev/null
    if [ $? -ne 0 ]; then
        echo "❌ Syntax error detected in: $file."
        exit 1
    fi
done

printf "✅ Syntax is valid!\n"

git add .

exit 0