#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.php$')

if [ -z "$STAGED_FILES" ]; then
    printf "ℹ️  Syntax check not needed, no PHP files staged\n"

    exit 0
fi

for file in $STAGED_FILES; do
    php -l "$file" > /dev/null
    if [ $? -ne 0 ]; then
        echo "❌ Syntax error detected in: $file."
        exit 1
    fi
done

printf "✅ Syntax is valid!\n"

exit 0